# Replace with your credentials
unset QUADS_SERVER
unset QUADS_USERNAME
unset QUADS_PASSWORD
unset QUADS_OWNER
unset QUADS_CLOUD
unset QUADS_ASSIGNMENT_ID
unset QUADS_DESCRIPTION
unset QUADS_QINQ
unset QUADS_WIPE
